version: '3.8'

services:
  links:
    restart: always
    container_name: ozon_fintech
    build: ./
    # Так как docker-compose, к сожалению, не дает передавать флаги командной строки,
    # то их приходится указывать здесь в файле.

    # Раскомментируйте нужную строку для работы в режимах:

    # Режим работы, где в качестве хранилища POSTGRES
    command: ./Links -db_type POSTGRES

    # Режим работы, где в качестве хранилища STORAGE(собственное хранилище)
#    command: ./Links -db_type STORAGE

    ports:
      - "8000:8080"
    depends_on:
      - db

  db:
    restart: unless-stopped
    image: postgres:latest
    container_name: clair_postgres

    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "ozon_fintech"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
      - ./schema/init.up.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5436:5432"